<?php

declare(strict_types=1);

defined('APP_BOOTED') || exit('No direct access.');

use App\Agreements\DigitalAgreementGenerator;
use App\Core\Database;

require dirname(__DIR__) . '/_portal_layout.php';
$owner = require_owner();

if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['do'] ?? '') === 'generate') {
    $leadId = (int) ($_POST['lead_id'] ?? 0);
    $roomId = (int) ($_POST['room_id'] ?? 0);

    $owned = Database::run('SELECT COUNT(*) FROM rooms WHERE id = ? AND owner_name = ?', [$roomId, $owner])->fetchColumn() > 0;
    if (!$owned) {
        set_flash('danger', 'That room is not on your account.');
    } else {
        try {
            $agreement = DigitalAgreementGenerator::generate($leadId, $roomId);
            set_flash('success', 'Agreement generated by ' . $agreement['generated_by_model']
                . '. Tenant opens it in their portal (access code: ' . $agreement['access_code'] . ').');
        } catch (\Throwable $e) {
            set_flash('danger', 'Generation failed: ' . $e->getMessage());
        }
    }
    header('Location: /owner/agreements');
    exit;
}

$agreements = Database::run(
    'SELECT a.*, l.name AS tenant_name, r.name AS room_name
     FROM digital_agreements a
     JOIN leads l ON l.id = a.lead_id
     LEFT JOIN rooms r ON r.id = a.room_id
     WHERE r.owner_name = ?
     ORDER BY a.id DESC',
    [$owner]
)->fetchAll();

$rooms = Database::run('SELECT id, name, location AS area FROM rooms WHERE owner_name = ? ORDER BY name', [$owner])->fetchAll();
$bookedLeads = Database::run(
    'SELECT DISTINCT l.id, l.name, l.wa_phone FROM leads l
     JOIN bookings b ON b.lead_id = l.id
     JOIN rooms r ON r.id = b.room_id
     WHERE r.owner_name = ?
     ORDER BY l.name',
    [$owner]
)->fetchAll();

portal_header('owner', 'Agreements', 'agreements');
?>
<div class="portal-hero">
    <div class="tagline">Everything in writing — automatically.</div>
    <h1>Digital agreements</h1>
    <p>Generated from the room and tenant details in seconds; acknowledged by the tenant with a typed name and timestamp.</p>
</div>

<div class="belive-card" style="margin-bottom:16px">
    <div class="belive-card-title">✨ Generate an agreement</div>
    <?php if ($bookedLeads === []): ?>
        <p class="belive-muted">Once a tenant books one of your rooms, you can generate their agreement here.</p>
    <?php else: ?>
        <form method="post" action="/owner/agreements" style="display:flex; gap:12px; flex-wrap:wrap; align-items:flex-end">
            <input type="hidden" name="do" value="generate">
            <div class="belive-field" style="flex:1; min-width:200px; margin:0">
                <label>Tenant</label>
                <select name="lead_id">
                    <?php foreach ($bookedLeads as $lead): ?>
                        <option value="<?= (int) $lead['id'] ?>"><?= e($lead['name'] ?: $lead['wa_phone']) ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="belive-field" style="flex:1; min-width:200px; margin:0">
                <label>Room</label>
                <select name="room_id">
                    <?php foreach ($rooms as $room): ?>
                        <option value="<?= (int) $room['id'] ?>"><?= e($room['name']) ?> — <?= e($room['area']) ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <button type="submit" class="belive-btn-primary">Generate</button>
        </form>
    <?php endif; ?>
</div>

<div class="belive-card">
    <div class="belive-card-title">📄 Issued agreements</div>
    <?php if ($agreements === []): ?>
        <p class="belive-muted">None yet.</p>
    <?php else: ?>
        <table class="belive-table">
            <thead><tr><th>#</th><th>Tenant</th><th>Room</th><th>Status</th><th>Acknowledged</th><th>Access code</th></tr></thead>
            <tbody>
            <?php foreach ($agreements as $agreement): ?>
                <tr>
                    <td><?= (int) $agreement['id'] ?></td>
                    <td><?= e($agreement['tenant_name']) ?></td>
                    <td style="font-size:13px"><?= e($agreement['room_name'] ?? '—') ?></td>
                    <td>
                        <span class="belive-badge <?= $agreement['status'] === 'acknowledged' ? '' : 'orange' ?>"><?= e($agreement['status']) ?></span>
                    </td>
                    <td style="font-size:13px">
                        <?= $agreement['acknowledged_at'] ? e($agreement['acknowledged_name'] . ' · ' . $agreement['acknowledged_at']) : '—' ?>
                    </td>
                    <td><code><?= e($agreement['access_code']) ?></code></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <p class="belive-muted" style="font-size:12px; margin-top:10px">
            Acknowledgement = typed name + checkbox + server timestamp. Not a cryptographic e-signature —
            a clear, dated record both sides can see.
        </p>
    <?php endif; ?>
</div>
<?php portal_footer();
