<?php

declare(strict_types=1);

defined('APP_BOOTED') || exit('No direct access.');

use App\AI\Memory\EpisodicLogger;
use App\Core\Auth;
use App\Core\Database;

require dirname(__DIR__) . '/_layout.php';
Auth::requireAdmin();

$id = (int) ($_GET['id'] ?? $_POST['id'] ?? 0);
$post = Database::run(
    'SELECT p.*, r.name AS room_name, r.location AS area, rp.price FROM content_posts p
     LEFT JOIN rooms r ON r.id = p.room_id
     LEFT JOIN room_pricing rp ON rp.room_id = r.id AND rp.tenure = \'monthly\'
     WHERE p.id = ?',
    [$id]
)->fetch();

if ($post === false) {
    set_flash('danger', 'Draft not found.');
    header('Location: /admin/content');
    exit;
}

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    Auth::requireCsrf();
    $action = $_POST['do'] ?? '';

    if ($action === 'approve' && $post['status'] === 'draft') {
        Database::run("UPDATE content_posts SET status = 'approved' WHERE id = ?", [$id]);
        set_flash('success', 'Approved — copy the caption to the platform, then mark it posted.');
    } elseif ($action === 'mark_posted' && $post['status'] !== 'posted') {
        Database::run("UPDATE content_posts SET status = 'posted', posted_at = NOW() WHERE id = ?", [$id]);
        EpisodicLogger::activity('content_posted', 'content_creation', $post['generated_by_model'], null, "post #$id on {$post['platform']}");
        set_flash('success', 'Marked as posted — it counts on the dashboard now.');
    }
    header("Location: /admin/content/preview?id=$id");
    exit;
}

admin_header('Post preview', 'content');
?>
<div class="belive-page-head">
    <h1>Post preview</h1>
    <a class="belive-btn-ghost" href="/admin/content">← Content studio</a>
</div>

<div class="belive-row">
    <div class="belive-col" style="max-width:520px">
        <div class="belive-card">
            <div class="belive-card-title">
                <?= ['facebook' => '📘', 'instagram' => '📷', 'tiktok' => '🎵'][$post['platform']] ?>
                <?= e(ucfirst($post['platform'])) ?> draft
                <span class="belive-badge <?= $post['status'] === 'posted' ? '' : 'orange' ?>"><?= e($post['status']) ?></span>
            </div>

            <div style="background:var(--belive-cream); border-radius:12px; padding:16px; white-space:pre-wrap; font-size:14px; line-height:1.6"><?= e($post['caption']) ?></div>

            <div class="belive-muted" style="font-size:12.5px; margin-top:10px">
                Generated by <code><?= e($post['generated_by_model']) ?></code>
                from <?= e($post['room_name'] ? "{$post['room_name']} — {$post['area']}, RM" . number_format((float) $post['price']) . '/mo' : 'room data') ?>
                · <?= e($post['created_at']) ?>
            </div>

            <div style="display:flex; gap:8px; margin-top:16px; flex-wrap:wrap">
                <?php if ($post['status'] === 'draft'): ?>
                    <form method="post"><input type="hidden" name="csrf_token" value="<?= e(Auth::csrfToken()) ?>"><input type="hidden" name="id" value="<?= $id ?>"><input type="hidden" name="do" value="approve">
                        <button type="submit" class="belive-btn-secondary">Approve</button>
                    </form>
                <?php endif; ?>
                <?php if ($post['status'] !== 'posted'): ?>
                    <form method="post"><input type="hidden" name="csrf_token" value="<?= e(Auth::csrfToken()) ?>"><input type="hidden" name="id" value="<?= $id ?>"><input type="hidden" name="do" value="mark_posted">
                        <button type="submit" class="belive-btn-primary">Mark as posted</button>
                    </form>
                <?php endif; ?>
            </div>
        </div>
    </div>

    <div class="belive-col">
        <div class="belive-card">
            <div class="belive-card-title">ℹ Publishing model</div>
            <p style="font-size:13.5px" class="belive-muted">
                Caption generation is fully automated from live room metrics. Publishing is
                <strong>semi-automated by design</strong>: Meta page publishing needs a reviewed Meta app
                and TikTok exposes no third-party publish API, so within the competition budget the
                honest flow is generate → approve → paste to platform → mark posted. The same module is
                integration-ready for the Meta publish API once a reviewed app exists.
            </p>
        </div>
    </div>
</div>
<?php admin_footer();
