-- PostgreSQL baseline for the application schema through MySQL migration 048.

-- Run via database/migrate.php or the converted import, inside a transaction.

CREATE COLLATION belive_unicode_ci (provider = icu, locale = 'und-u-ks-level1', deterministic = false);

CREATE FUNCTION belive_touch_updated_at() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW IS DISTINCT FROM OLD AND NEW.updated_at IS NOT DISTINCT FROM OLD.updated_at THEN NEW.updated_at = statement_timestamp() AT TIME ZONE 'UTC'; END IF; RETURN NEW; END $$;

CREATE TABLE "agreement_events" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" BETWEEN 0 AND 4294967295),
    "agreement_id" bigint NOT NULL CHECK ("agreement_id" BETWEEN 0 AND 4294967295),
    "actor_role" varchar(6) COLLATE belive_unicode_ci NOT NULL CHECK ("actor_role" IN ('admin','owner','tenant','system')),
    "actor_name" varchar(120) COLLATE belive_unicode_ci DEFAULT NULL,
    "action" varchar(40) COLLATE belive_unicode_ci NOT NULL,
    "from_status" varchar(20) COLLATE belive_unicode_ci DEFAULT NULL,
    "to_status" varchar(20) COLLATE belive_unicode_ci DEFAULT NULL,
    "note" varchar(500) COLLATE belive_unicode_ci DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL DEFAULT (statement_timestamp() AT TIME ZONE 'UTC'),
    PRIMARY KEY ("id")
);

ALTER TABLE "agreement_events" ENABLE ROW LEVEL SECURITY;

CREATE TABLE "ai_activity_log" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" BETWEEN 0 AND 4294967295),
    "action" varchar(80) COLLATE belive_unicode_ci NOT NULL,
    "phase" varchar(30) COLLATE belive_unicode_ci DEFAULT NULL,
    "model_used" varchar(60) COLLATE belive_unicode_ci DEFAULT NULL,
    "lead_id" bigint DEFAULT NULL CHECK ("lead_id" BETWEEN 0 AND 4294967295),
    "detail" text COLLATE belive_unicode_ci DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL DEFAULT (statement_timestamp() AT TIME ZONE 'UTC'),
    PRIMARY KEY ("id")
);

ALTER TABLE "ai_activity_log" ENABLE ROW LEVEL SECURITY;

CREATE TABLE "ai_custom_models" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" BETWEEN 0 AND 4294967295),
    "model_key" varchar(100) COLLATE belive_unicode_ci NOT NULL,
    "provider" varchar(10) COLLATE belive_unicode_ci NOT NULL CHECK ("provider" IN ('anthropic','gemini','openai','openrouter')),
    "label" varchar(100) COLLATE belive_unicode_ci NOT NULL,
    "purpose" varchar(200) COLLATE belive_unicode_ci NOT NULL DEFAULT '',
    "cost_tier" varchar(8) COLLATE belive_unicode_ci NOT NULL DEFAULT 'standard' CHECK ("cost_tier" IN ('economy','standard','premium')),
    "created_at" timestamp without time zone NOT NULL DEFAULT (statement_timestamp() AT TIME ZONE 'UTC'),
    PRIMARY KEY ("id"),
    CONSTRAINT "ai_custom_models_model_key" UNIQUE ("model_key")
);

ALTER TABLE "ai_custom_models" ENABLE ROW LEVEL SECURITY;

CREATE TABLE "ai_feedback" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" BETWEEN 0 AND 4294967295),
    "interaction_id" bigint DEFAULT NULL CHECK ("interaction_id" BETWEEN 0 AND 4294967295),
    "lead_id" bigint DEFAULT NULL CHECK ("lead_id" BETWEEN 0 AND 4294967295),
    "feedback_source" varchar(19) COLLATE belive_unicode_ci NOT NULL CHECK ("feedback_source" IN ('admin_flag','customer_correction','implicit_repeat','implicit_dropoff','pattern_detection','system_detection')),
    "error_type" varchar(18) COLLATE belive_unicode_ci NOT NULL CHECK ("error_type" IN ('wrong_price','wrong_availability','wrong_tone','missed_intent','poor_sequencing','low_engagement')),
    "comment" text COLLATE belive_unicode_ci DEFAULT NULL,
    "processed" smallint NOT NULL DEFAULT 0,
    "created_at" timestamp without time zone NOT NULL DEFAULT (statement_timestamp() AT TIME ZONE 'UTC'),
    "feedback_hash" char(64) COLLATE belive_unicode_ci DEFAULT NULL,
    "memory_id" bigint DEFAULT NULL CHECK ("memory_id" BETWEEN 0 AND 4294967295),
    PRIMARY KEY ("id"),
    CONSTRAINT "ai_feedback_uq_feedback_hash" UNIQUE ("feedback_hash")
);

ALTER TABLE "ai_feedback" ENABLE ROW LEVEL SECURITY;

CREATE TABLE "ai_interactions" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" BETWEEN 0 AND 4294967295),
    "lead_id" bigint DEFAULT NULL CHECK ("lead_id" BETWEEN 0 AND 4294967295),
    "phase" varchar(16) COLLATE belive_unicode_ci NOT NULL CHECK ("phase" IN ('lead_gen','conversion','content_creation')),
    "skill" varchar(10) COLLATE belive_unicode_ci NOT NULL CHECK ("skill" IN ('understand','decide','create','automate')),
    "model_used" varchar(60) COLLATE belive_unicode_ci NOT NULL,
    "direction" varchar(8) COLLATE belive_unicode_ci NOT NULL DEFAULT 'internal' CHECK ("direction" IN ('inbound','outbound','internal')),
    "message_in" text COLLATE belive_unicode_ci DEFAULT NULL,
    "message_out" text COLLATE belive_unicode_ci DEFAULT NULL,
    "message_kind" varchar(40) COLLATE belive_unicode_ci DEFAULT NULL,
    "intent" varchar(60) COLLATE belive_unicode_ci DEFAULT NULL,
    "entities" jsonb DEFAULT NULL,
    "reasoning" text COLLATE belive_unicode_ci DEFAULT NULL,
    "memory_used" jsonb DEFAULT NULL,
    "response_ms" bigint DEFAULT NULL CHECK ("response_ms" BETWEEN 0 AND 4294967295),
    "flagged" smallint NOT NULL DEFAULT 0,
    "created_at" timestamp without time zone NOT NULL DEFAULT (statement_timestamp() AT TIME ZONE 'UTC'),
    PRIMARY KEY ("id")
);

ALTER TABLE "ai_interactions" ENABLE ROW LEVEL SECURITY;

CREATE TABLE "ai_learned_memory" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" BETWEEN 0 AND 4294967295),
    "context_tag" varchar(60) COLLATE belive_unicode_ci NOT NULL DEFAULT 'general',
    "rule_type" varchar(10) COLLATE belive_unicode_ci NOT NULL DEFAULT 'fact' CHECK ("rule_type" IN ('fact','sequencing','strategy','tone')),
    "learned_rule" text COLLATE belive_unicode_ci NOT NULL,
    "source_feedback_id" bigint DEFAULT NULL CHECK ("source_feedback_id" BETWEEN 0 AND 4294967295),
    "confidence_score" decimal(4,3) NOT NULL DEFAULT 0.600,
    "times_reinforced" bigint NOT NULL DEFAULT 0 CHECK ("times_reinforced" BETWEEN 0 AND 4294967295),
    "times_contradicted" bigint NOT NULL DEFAULT 0 CHECK ("times_contradicted" BETWEEN 0 AND 4294967295),
    "active" smallint NOT NULL DEFAULT 1,
    "last_used_at" timestamp without time zone DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL DEFAULT (statement_timestamp() AT TIME ZONE 'UTC'),
    "updated_at" timestamp without time zone NOT NULL DEFAULT (statement_timestamp() AT TIME ZONE 'UTC'),
    "lesson_hash" char(64) COLLATE belive_unicode_ci DEFAULT NULL,
    "lesson_key" varchar(160) COLLATE belive_unicode_ci DEFAULT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "ai_learned_memory_uq_lesson_hash" UNIQUE ("lesson_hash")
);

ALTER TABLE "ai_learned_memory" ENABLE ROW LEVEL SECURITY;

CREATE TABLE "ai_model_config" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" BETWEEN 0 AND 4294967295),
    "phase" varchar(16) COLLATE belive_unicode_ci NOT NULL CHECK ("phase" IN ('lead_gen','conversion','content_creation')),
    "model_key" varchar(100) COLLATE belive_unicode_ci NOT NULL,
    "updated_at" timestamp without time zone NOT NULL DEFAULT (statement_timestamp() AT TIME ZONE 'UTC'),
    PRIMARY KEY ("id"),
    CONSTRAINT "ai_model_config_phase" UNIQUE ("phase")
);

ALTER TABLE "ai_model_config" ENABLE ROW LEVEL SECURITY;

CREATE TABLE "api_credentials" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" BETWEEN 0 AND 4294967295),
    "service" varchar(10) COLLATE belive_unicode_ci NOT NULL CHECK ("service" IN ('whatsapp','anthropic','gemini','meta_graph','instagram','openai','openrouter','tiktok')),
    "label" varchar(100) COLLATE belive_unicode_ci NOT NULL DEFAULT '',
    "encrypted_key" text COLLATE belive_unicode_ci NOT NULL,
    "meta" jsonb DEFAULT NULL,
    "is_active" smallint NOT NULL DEFAULT 0,
    "last_tested_at" timestamp without time zone DEFAULT NULL,
    "test_status" varchar(6) COLLATE belive_unicode_ci DEFAULT NULL CHECK ("test_status" IN ('ok','failed')),
    "test_detail" varchar(500) COLLATE belive_unicode_ci DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL DEFAULT (statement_timestamp() AT TIME ZONE 'UTC'),
    "updated_at" timestamp without time zone NOT NULL DEFAULT (statement_timestamp() AT TIME ZONE 'UTC'),
    PRIMARY KEY ("id")
);

ALTER TABLE "api_credentials" ENABLE ROW LEVEL SECURITY;

CREATE TABLE "app_settings" (
    "setting_key" varchar(80) COLLATE belive_unicode_ci NOT NULL,
    "setting_value" text COLLATE belive_unicode_ci DEFAULT NULL,
    "updated_by" varchar(60) COLLATE belive_unicode_ci DEFAULT NULL,
    "updated_at" timestamp without time zone NOT NULL DEFAULT (statement_timestamp() AT TIME ZONE 'UTC'),
    PRIMARY KEY ("setting_key")
);

ALTER TABLE "app_settings" ENABLE ROW LEVEL SECURITY;

CREATE TABLE "bookings" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" BETWEEN 0 AND 4294967295),
    "lead_id" bigint NOT NULL CHECK ("lead_id" BETWEEN 0 AND 4294967295),
    "room_id" bigint DEFAULT NULL CHECK ("room_id" BETWEEN 0 AND 4294967295),
    "viewing_datetime" timestamp without time zone NOT NULL,
    "viewing_mode" varchar(10) COLLATE belive_unicode_ci DEFAULT NULL CHECK ("viewing_mode" IN ('video_call','in_person')),
    "staff_id" bigint DEFAULT NULL CHECK ("staff_id" BETWEEN 0 AND 4294967295),
    "status" varchar(9) COLLATE belive_unicode_ci NOT NULL DEFAULT 'pending' CHECK ("status" IN ('pending','confirmed','cancelled','completed')),
    "confirmation_sent" smallint NOT NULL DEFAULT 0,
    "notes" text COLLATE belive_unicode_ci DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL DEFAULT (statement_timestamp() AT TIME ZONE 'UTC'),
    "updated_at" timestamp without time zone NOT NULL DEFAULT (statement_timestamp() AT TIME ZONE 'UTC'),
    PRIMARY KEY ("id")
);

ALTER TABLE "bookings" ENABLE ROW LEVEL SECURITY;

CREATE TABLE "content_post_metrics" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" BETWEEN 0 AND 4294967295),
    "content_post_id" bigint NOT NULL CHECK ("content_post_id" BETWEEN 0 AND 4294967295),
    "platform" varchar(9) COLLATE belive_unicode_ci NOT NULL CHECK ("platform" IN ('facebook','instagram','tiktok')),
    "captured_on" date NOT NULL,
    "captured_at" timestamp without time zone NOT NULL,
    "source" varchar(11) COLLATE belive_unicode_ci NOT NULL DEFAULT 'platform' CHECK ("source" IN ('platform','unavailable')),
    "views" bigint DEFAULT NULL CHECK ("views" BETWEEN 0 AND 4294967295),
    "likes" bigint DEFAULT NULL CHECK ("likes" BETWEEN 0 AND 4294967295),
    "comments" bigint DEFAULT NULL CHECK ("comments" BETWEEN 0 AND 4294967295),
    "shares" bigint DEFAULT NULL CHECK ("shares" BETWEEN 0 AND 4294967295),
    "note" varchar(255) COLLATE belive_unicode_ci DEFAULT NULL,
    "raw" text COLLATE belive_unicode_ci DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL DEFAULT (statement_timestamp() AT TIME ZONE 'UTC'),
    PRIMARY KEY ("id"),
    CONSTRAINT "content_post_metrics_uq_post_day" UNIQUE ("content_post_id","captured_on")
);

ALTER TABLE "content_post_metrics" ENABLE ROW LEVEL SECURITY;

CREATE TABLE "content_posts" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" BETWEEN 0 AND 4294967295),
    "platform" varchar(9) COLLATE belive_unicode_ci NOT NULL CHECK ("platform" IN ('facebook','instagram','tiktok')),
    "media_kind" varchar(5) COLLATE belive_unicode_ci NOT NULL DEFAULT 'image' CHECK ("media_kind" IN ('image','video')),
    "room_id" bigint DEFAULT NULL CHECK ("room_id" BETWEEN 0 AND 4294967295),
    "caption" text COLLATE belive_unicode_ci NOT NULL,
    "status" varchar(9) COLLATE belive_unicode_ci NOT NULL DEFAULT 'draft' CHECK ("status" IN ('draft','scheduled','approved','rejected','posted')),
    "review_version" bigint NOT NULL DEFAULT 1 CHECK ("review_version" BETWEEN 0 AND 4294967295),
    "reviewed_by" varchar(60) COLLATE belive_unicode_ci DEFAULT NULL,
    "reviewed_at" timestamp without time zone DEFAULT NULL,
    "review_note" varchar(500) COLLATE belive_unicode_ci DEFAULT NULL,
    "publish_status" varchar(10) COLLATE belive_unicode_ci DEFAULT NULL CHECK ("publish_status" IN ('published','simulated','failed','publishing','uncertain')),
    "publish_error" varchar(500) COLLATE belive_unicode_ci DEFAULT NULL,
    "external_post_id" varchar(120) COLLATE belive_unicode_ci DEFAULT NULL,
    "image_url" varchar(255) COLLATE belive_unicode_ci DEFAULT NULL,
    "video_url" varchar(255) COLLATE belive_unicode_ci DEFAULT NULL,
    "video_script" text COLLATE belive_unicode_ci DEFAULT NULL,
    "generated_by_model" varchar(60) COLLATE belive_unicode_ci NOT NULL,
    "generated_via" varchar(6) COLLATE belive_unicode_ci NOT NULL DEFAULT 'manual' CHECK ("generated_via" IN ('manual','cron')),
    "posted_at" timestamp without time zone DEFAULT NULL,
    "scheduled_for" timestamp without time zone DEFAULT NULL,
    "scheduled_by" varchar(60) COLLATE belive_unicode_ci DEFAULT NULL,
    "schedule_source" varchar(9) COLLATE belive_unicode_ci DEFAULT NULL CHECK ("schedule_source" IN ('suggested','custom','auto')),
    "created_at" timestamp without time zone NOT NULL DEFAULT (statement_timestamp() AT TIME ZONE 'UTC'),
    "creative_meta" jsonb DEFAULT NULL,
    "publish_attempts" bigint NOT NULL DEFAULT 0 CHECK ("publish_attempts" BETWEEN 0 AND 4294967295),
    "publish_attempted_at" timestamp without time zone DEFAULT NULL,
    "next_retry_at" timestamp without time zone DEFAULT NULL,
    PRIMARY KEY ("id")
);

ALTER TABLE "content_posts" ENABLE ROW LEVEL SECURITY;

CREATE TABLE "digital_agreements" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" BETWEEN 0 AND 4294967295),
    "lead_id" bigint NOT NULL CHECK ("lead_id" BETWEEN 0 AND 4294967295),
    "room_id" bigint DEFAULT NULL CHECK ("room_id" BETWEEN 0 AND 4294967295),
    "tenure" varchar(8) COLLATE belive_unicode_ci DEFAULT NULL CHECK ("tenure" IN ('monthly','6_month','12_month')),
    "starts_on" date DEFAULT NULL,
    "ends_on" date DEFAULT NULL,
    "monthly_rent_rm" decimal(10,2) DEFAULT NULL,
    "deposit_rm" decimal(10,2) NOT NULL DEFAULT 0.00,
    "agreement_text" text COLLATE belive_unicode_ci NOT NULL,
    "status" varchar(13) COLLATE belive_unicode_ci NOT NULL DEFAULT 'draft' CHECK ("status" IN ('draft','owner_review','admin_review','tenant_review','completed','cancelled')),
    "stage_version" bigint NOT NULL DEFAULT 1 CHECK ("stage_version" BETWEEN 0 AND 4294967295),
    "owner_name" varchar(120) COLLATE belive_unicode_ci DEFAULT NULL,
    "owner_full_name" varchar(120) COLLATE belive_unicode_ci DEFAULT NULL,
    "owner_ic_enc" text COLLATE belive_unicode_ci DEFAULT NULL,
    "owner_ic_last4" varchar(4) COLLATE belive_unicode_ci DEFAULT NULL,
    "owner_email" varchar(120) COLLATE belive_unicode_ci DEFAULT NULL,
    "owner_phone" varchar(40) COLLATE belive_unicode_ci DEFAULT NULL,
    "owner_address" varchar(255) COLLATE belive_unicode_ci DEFAULT NULL,
    "owner_bank_name" varchar(80) COLLATE belive_unicode_ci DEFAULT NULL,
    "owner_bank_holder" varchar(120) COLLATE belive_unicode_ci DEFAULT NULL,
    "owner_bank_account_enc" text COLLATE belive_unicode_ci DEFAULT NULL,
    "owner_bank_account_last4" varchar(4) COLLATE belive_unicode_ci DEFAULT NULL,
    "owner_extra_terms" text COLLATE belive_unicode_ci DEFAULT NULL,
    "owner_signed_name" varchar(120) COLLATE belive_unicode_ci DEFAULT NULL,
    "owner_signed_at" timestamp without time zone DEFAULT NULL,
    "sent_to_owner_at" timestamp without time zone DEFAULT NULL,
    "admin_review_note" varchar(500) COLLATE belive_unicode_ci DEFAULT NULL,
    "admin_reviewed_by" varchar(120) COLLATE belive_unicode_ci DEFAULT NULL,
    "admin_reviewed_at" timestamp without time zone DEFAULT NULL,
    "sent_to_tenant_at" timestamp without time zone DEFAULT NULL,
    "tenant_note" varchar(500) COLLATE belive_unicode_ci DEFAULT NULL,
    "acknowledged_name" varchar(120) COLLATE belive_unicode_ci DEFAULT NULL,
    "acknowledged_at" timestamp without time zone DEFAULT NULL,
    "access_code" varchar(16) COLLATE belive_unicode_ci NOT NULL,
    "generated_by_model" varchar(60) COLLATE belive_unicode_ci DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL DEFAULT (statement_timestamp() AT TIME ZONE 'UTC'),
    PRIMARY KEY ("id"),
    CONSTRAINT "digital_agreements_uq_access_code" UNIQUE ("access_code")
);

ALTER TABLE "digital_agreements" ENABLE ROW LEVEL SECURITY;

CREATE TABLE "electric_bills" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" BETWEEN 0 AND 4294967295),
    "meter_id" bigint NOT NULL CHECK ("meter_id" BETWEEN 0 AND 4294967295),
    "lead_id" bigint NOT NULL CHECK ("lead_id" BETWEEN 0 AND 4294967295),
    "period_start" date NOT NULL,
    "period_end" date NOT NULL,
    "previous_reading" decimal(10,2) NOT NULL,
    "current_reading" decimal(10,2) NOT NULL,
    "units_kwh" decimal(10,2) NOT NULL,
    "rate_rm_per_kwh" decimal(6,4) NOT NULL,
    "standing_charge_rm" decimal(8,2) NOT NULL DEFAULT 0.00,
    "amount_rm" decimal(10,2) NOT NULL,
    "status" varchar(6) COLLATE belive_unicode_ci NOT NULL DEFAULT 'unpaid' CHECK ("status" IN ('unpaid','paid','waived')),
    "reading_source" varchar(11) COLLATE belive_unicode_ci NOT NULL DEFAULT 'manual' CHECK ("reading_source" IN ('smart_meter','manual')),
    "issued_on" date NOT NULL,
    "due_on" date NOT NULL,
    "paid_at" timestamp without time zone DEFAULT NULL,
    "notes" varchar(255) COLLATE belive_unicode_ci DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL DEFAULT (statement_timestamp() AT TIME ZONE 'UTC'),
    "updated_at" timestamp without time zone NOT NULL DEFAULT (statement_timestamp() AT TIME ZONE 'UTC'),
    PRIMARY KEY ("id"),
    CONSTRAINT "electric_bills_uq_bill_period" UNIQUE ("meter_id","period_start")
);

ALTER TABLE "electric_bills" ENABLE ROW LEVEL SECURITY;

CREATE TABLE "electric_meters" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" BETWEEN 0 AND 4294967295),
    "room_id" bigint NOT NULL CHECK ("room_id" BETWEEN 0 AND 4294967295),
    "meter_serial" varchar(40) COLLATE belive_unicode_ci NOT NULL,
    "tariff_rm_per_kwh" decimal(6,4) NOT NULL DEFAULT 0.5000,
    "standing_charge_rm" decimal(8,2) NOT NULL DEFAULT 0.00,
    "installed_on" date DEFAULT NULL,
    "active" smallint NOT NULL DEFAULT 1,
    "created_at" timestamp without time zone NOT NULL DEFAULT (statement_timestamp() AT TIME ZONE 'UTC'),
    "updated_at" timestamp without time zone NOT NULL DEFAULT (statement_timestamp() AT TIME ZONE 'UTC'),
    PRIMARY KEY ("id"),
    CONSTRAINT "electric_meters_uq_meter_room" UNIQUE ("room_id"),
    CONSTRAINT "electric_meters_uq_meter_serial" UNIQUE ("meter_serial")
);

ALTER TABLE "electric_meters" ENABLE ROW LEVEL SECURITY;

CREATE TABLE "leads" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" BETWEEN 0 AND 4294967295),
    "wa_phone" varchar(32) COLLATE belive_unicode_ci NOT NULL,
    "name" varchar(120) COLLATE belive_unicode_ci DEFAULT NULL,
    "source_channel" varchar(14) COLLATE belive_unicode_ci NOT NULL CHECK ("source_channel" IN ('whatsapp','social','website','listing_portal','referral','tiktok')),
    "status" varchar(9) COLLATE belive_unicode_ci NOT NULL DEFAULT 'new' CHECK ("status" IN ('new','qualified','converted')),
    "location" varchar(100) COLLATE belive_unicode_ci DEFAULT NULL,
    "budget" varchar(50) COLLATE belive_unicode_ci DEFAULT NULL,
    "move_in_date" varchar(50) COLLATE belive_unicode_ci DEFAULT NULL,
    "room_type" varchar(50) COLLATE belive_unicode_ci DEFAULT NULL,
    "tenant_profile" varchar(50) COLLATE belive_unicode_ci DEFAULT NULL,
    "closing_probability" smallint DEFAULT NULL CHECK ("closing_probability" BETWEEN 0 AND 255),
    "lead_signals" jsonb DEFAULT NULL,
    "ai_recommendation" text COLLATE belive_unicode_ci DEFAULT NULL,
    "notes" text COLLATE belive_unicode_ci DEFAULT NULL,
    "referral_code_used" varchar(12) COLLATE belive_unicode_ci DEFAULT NULL,
    "merged_into_lead_id" bigint DEFAULT NULL CHECK ("merged_into_lead_id" BETWEEN 0 AND 4294967295),
    "last_contact_at" timestamp without time zone DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL DEFAULT (statement_timestamp() AT TIME ZONE 'UTC'),
    "updated_at" timestamp without time zone NOT NULL DEFAULT (statement_timestamp() AT TIME ZONE 'UTC'),
    "enquired_room_id" bigint DEFAULT NULL CHECK ("enquired_room_id" BETWEEN 0 AND 4294967295),
    "preferred_tenure" varchar(8) COLLATE belive_unicode_ci DEFAULT NULL CHECK ("preferred_tenure" IN ('monthly','6_month','12_month')),
    PRIMARY KEY ("id"),
    CONSTRAINT "leads_uq_wa_phone" UNIQUE ("wa_phone")
);

ALTER TABLE "leads" ENABLE ROW LEVEL SECURITY;

CREATE TABLE "migrations" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" BETWEEN 0 AND 4294967295),
    "filename" varchar(120) COLLATE belive_unicode_ci NOT NULL,
    "applied_at" timestamp without time zone NOT NULL DEFAULT (statement_timestamp() AT TIME ZONE 'UTC'),
    PRIMARY KEY ("id"),
    CONSTRAINT "migrations_filename" UNIQUE ("filename")
);

ALTER TABLE "migrations" ENABLE ROW LEVEL SECURITY;

CREATE TABLE "move_in_logs" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" BETWEEN 0 AND 4294967295),
    "room_id" bigint NOT NULL CHECK ("room_id" BETWEEN 0 AND 4294967295),
    "lead_id" bigint DEFAULT NULL CHECK ("lead_id" BETWEEN 0 AND 4294967295),
    "photo_path" varchar(255) COLLATE belive_unicode_ci NOT NULL,
    "caption" varchar(255) COLLATE belive_unicode_ci DEFAULT NULL,
    "taken_at" timestamp without time zone NOT NULL,
    "uploaded_by" varchar(5) COLLATE belive_unicode_ci NOT NULL DEFAULT 'admin' CHECK ("uploaded_by" IN ('admin','owner')),
    "created_at" timestamp without time zone NOT NULL DEFAULT (statement_timestamp() AT TIME ZONE 'UTC'),
    PRIMARY KEY ("id")
);

ALTER TABLE "move_in_logs" ENABLE ROW LEVEL SECURITY;

CREATE TABLE "processed_webhook_messages" (
    "wamid" varchar(128) COLLATE belive_unicode_ci NOT NULL,
    "created_at" timestamp without time zone NOT NULL DEFAULT (statement_timestamp() AT TIME ZONE 'UTC'),
    PRIMARY KEY ("wamid")
);

ALTER TABLE "processed_webhook_messages" ENABLE ROW LEVEL SECURITY;

CREATE TABLE "properties" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" BETWEEN 0 AND 4294967295),
    "owner_name" varchar(120) COLLATE belive_unicode_ci NOT NULL,
    "name" varchar(120) COLLATE belive_unicode_ci NOT NULL,
    "location" varchar(100) COLLATE belive_unicode_ci NOT NULL,
    "address" varchar(255) COLLATE belive_unicode_ci NOT NULL,
    "description" text COLLATE belive_unicode_ci DEFAULT NULL,
    "review_status" varchar(8) COLLATE belive_unicode_ci NOT NULL DEFAULT 'pending' CHECK ("review_status" IN ('pending','approved','rejected')),
    "review_version" bigint NOT NULL DEFAULT 1 CHECK ("review_version" BETWEEN 0 AND 4294967295),
    "review_note" text COLLATE belive_unicode_ci DEFAULT NULL,
    "reviewed_by" varchar(120) COLLATE belive_unicode_ci DEFAULT NULL,
    "reviewed_at" timestamp without time zone DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL DEFAULT (statement_timestamp() AT TIME ZONE 'UTC'),
    "updated_at" timestamp without time zone NOT NULL DEFAULT (statement_timestamp() AT TIME ZONE 'UTC'),
    PRIMARY KEY ("id"),
    CONSTRAINT "properties_uq_owner_property" UNIQUE ("owner_name","name","location")
);

ALTER TABLE "properties" ENABLE ROW LEVEL SECURITY;

CREATE TABLE "property_units" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" BETWEEN 0 AND 4294967295),
    "property_id" bigint NOT NULL CHECK ("property_id" BETWEEN 0 AND 4294967295),
    "name" varchar(120) COLLATE belive_unicode_ci NOT NULL,
    "notes" varchar(255) COLLATE belive_unicode_ci DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL DEFAULT (statement_timestamp() AT TIME ZONE 'UTC'),
    "updated_at" timestamp without time zone NOT NULL DEFAULT (statement_timestamp() AT TIME ZONE 'UTC'),
    PRIMARY KEY ("id"),
    CONSTRAINT "property_units_uq_property_unit" UNIQUE ("property_id","name")
);

ALTER TABLE "property_units" ENABLE ROW LEVEL SECURITY;

CREATE TABLE "referral_redemptions" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" BETWEEN 0 AND 4294967295),
    "lead_id" bigint NOT NULL CHECK ("lead_id" BETWEEN 0 AND 4294967295),
    "reward_type" varchar(11) COLLATE belive_unicode_ci NOT NULL DEFAULT 'rent_credit' CHECK ("reward_type" IN ('rent_credit')),
    "points_spent" bigint NOT NULL CHECK ("points_spent" BETWEEN 0 AND 4294967295),
    "rent_credit_amount" decimal(8,2) NOT NULL,
    "status" varchar(9) COLLATE belive_unicode_ci NOT NULL DEFAULT 'requested' CHECK ("status" IN ('requested','approved','applied','rejected')),
    "requested_at" timestamp without time zone NOT NULL DEFAULT (statement_timestamp() AT TIME ZONE 'UTC'),
    "reviewed_at" timestamp without time zone DEFAULT NULL,
    "applied_at" timestamp without time zone DEFAULT NULL,
    "review_note" varchar(255) COLLATE belive_unicode_ci DEFAULT NULL,
    PRIMARY KEY ("id")
);

ALTER TABLE "referral_redemptions" ENABLE ROW LEVEL SECURITY;

CREATE TABLE "referrals" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" BETWEEN 0 AND 4294967295),
    "referral_code" varchar(12) COLLATE belive_unicode_ci NOT NULL,
    "referring_lead_id" bigint NOT NULL CHECK ("referring_lead_id" BETWEEN 0 AND 4294967295),
    "referred_lead_id" bigint DEFAULT NULL CHECK ("referred_lead_id" BETWEEN 0 AND 4294967295),
    "reward_room_id" bigint DEFAULT NULL CHECK ("reward_room_id" BETWEEN 0 AND 4294967295),
    "reward_room_name" varchar(120) COLLATE belive_unicode_ci DEFAULT NULL,
    "reward_property_name" varchar(120) COLLATE belive_unicode_ci DEFAULT NULL,
    "reward_points" bigint NOT NULL DEFAULT 0 CHECK ("reward_points" BETWEEN 0 AND 4294967295),
    "reward_status" varchar(8) COLLATE belive_unicode_ci NOT NULL DEFAULT 'pending' CHECK ("reward_status" IN ('pending','credited')),
    "clicks" bigint NOT NULL DEFAULT 0 CHECK ("clicks" BETWEEN 0 AND 4294967295),
    "credited_at" timestamp without time zone DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL DEFAULT (statement_timestamp() AT TIME ZONE 'UTC'),
    PRIMARY KEY ("id"),
    CONSTRAINT "referrals_referral_code" UNIQUE ("referral_code"),
    CONSTRAINT "referrals_uq_referral_referred_lead" UNIQUE ("referred_lead_id")
);

ALTER TABLE "referrals" ENABLE ROW LEVEL SECURITY;

CREATE TABLE "renewal_offers" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" BETWEEN 0 AND 4294967295),
    "agreement_id" bigint NOT NULL CHECK ("agreement_id" BETWEEN 0 AND 4294967295),
    "lead_id" bigint NOT NULL CHECK ("lead_id" BETWEEN 0 AND 4294967295),
    "room_id" bigint DEFAULT NULL CHECK ("room_id" BETWEEN 0 AND 4294967295),
    "owner_name" varchar(120) COLLATE belive_unicode_ci NOT NULL,
    "tenure" varchar(8) COLLATE belive_unicode_ci NOT NULL CHECK ("tenure" IN ('monthly','6_month','12_month')),
    "current_rent_rm" decimal(10,2) NOT NULL,
    "promo_rent_rm" decimal(10,2) NOT NULL,
    "starts_on" date NOT NULL,
    "ends_on" date NOT NULL,
    "message" varchar(500) COLLATE belive_unicode_ci DEFAULT NULL,
    "expires_on" date NOT NULL,
    "status" varchar(9) COLLATE belive_unicode_ci NOT NULL DEFAULT 'offered' CHECK ("status" IN ('offered','accepted','declined','withdrawn')),
    "responded_at" timestamp without time zone DEFAULT NULL,
    "response_note" varchar(500) COLLATE belive_unicode_ci DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL DEFAULT (statement_timestamp() AT TIME ZONE 'UTC'),
    "updated_at" timestamp without time zone NOT NULL DEFAULT (statement_timestamp() AT TIME ZONE 'UTC'),
    PRIMARY KEY ("id")
);

ALTER TABLE "renewal_offers" ENABLE ROW LEVEL SECURITY;

CREATE TABLE "room_amenities" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" BETWEEN 0 AND 4294967295),
    "room_id" bigint NOT NULL CHECK ("room_id" BETWEEN 0 AND 4294967295),
    "amenity" varchar(60) COLLATE belive_unicode_ci NOT NULL,
    PRIMARY KEY ("id")
);

ALTER TABLE "room_amenities" ENABLE ROW LEVEL SECURITY;

CREATE TABLE "room_images" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" BETWEEN 0 AND 4294967295),
    "room_id" bigint NOT NULL CHECK ("room_id" BETWEEN 0 AND 4294967295),
    "image_path" varchar(255) COLLATE belive_unicode_ci NOT NULL,
    "original_path" varchar(255) COLLATE belive_unicode_ci DEFAULT NULL,
    "enhanced_at" timestamp without time zone NULL DEFAULT NULL,
    "enhanced_by_model" varchar(80) COLLATE belive_unicode_ci DEFAULT NULL,
    "enhance_note" varchar(500) COLLATE belive_unicode_ci DEFAULT NULL,
    "enhance_recipe" text COLLATE belive_unicode_ci DEFAULT NULL,
    "sort_order" integer NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);

ALTER TABLE "room_images" ENABLE ROW LEVEL SECURITY;

CREATE TABLE "room_pricing" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" BETWEEN 0 AND 4294967295),
    "room_id" bigint NOT NULL CHECK ("room_id" BETWEEN 0 AND 4294967295),
    "tenure" varchar(8) COLLATE belive_unicode_ci NOT NULL CHECK ("tenure" IN ('monthly','6_month','12_month')),
    "price" decimal(8,2) NOT NULL,
    "is_best_value" smallint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id"),
    CONSTRAINT "room_pricing_uniq_room_tenure" UNIQUE ("room_id","tenure")
);

ALTER TABLE "room_pricing" ENABLE ROW LEVEL SECURITY;

CREATE TABLE "rooms" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" BETWEEN 0 AND 4294967295),
    "property_id" bigint DEFAULT NULL CHECK ("property_id" BETWEEN 0 AND 4294967295),
    "unit_id" bigint DEFAULT NULL CHECK ("unit_id" BETWEEN 0 AND 4294967295),
    "room_code" varchar(20) COLLATE belive_unicode_ci DEFAULT NULL,
    "name" varchar(120) COLLATE belive_unicode_ci NOT NULL,
    "property_name" varchar(120) COLLATE belive_unicode_ci DEFAULT NULL,
    "location" varchar(100) COLLATE belive_unicode_ci NOT NULL,
    "room_type" varchar(11) COLLATE belive_unicode_ci NOT NULL CHECK ("room_type" IN ('single','middle','master','studio','balcony','partitioned','mini_single')),
    "owner_name" varchar(120) COLLATE belive_unicode_ci DEFAULT NULL,
    "address" varchar(255) COLLATE belive_unicode_ci DEFAULT NULL,
    "description" text COLLATE belive_unicode_ci DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL DEFAULT (statement_timestamp() AT TIME ZONE 'UTC'),
    "status" varchar(9) COLLATE belive_unicode_ci NOT NULL DEFAULT 'available' CHECK ("status" IN ('available','occupied','reserved')),
    "deposit_amount" decimal(8,2) NOT NULL DEFAULT 0.00,
    "referral_reward_points" bigint NOT NULL DEFAULT 50 CHECK ("referral_reward_points" BETWEEN 0 AND 4294967295),
    "available_from" date DEFAULT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "rooms_room_code" UNIQUE ("room_code")
);

ALTER TABLE "rooms" ENABLE ROW LEVEL SECURITY;

CREATE TABLE "social_replies" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" BETWEEN 0 AND 4294967295),
    "platform" varchar(9) COLLATE belive_unicode_ci NOT NULL CHECK ("platform" IN ('facebook','instagram')),
    "event_type" varchar(14) COLLATE belive_unicode_ci NOT NULL CHECK ("event_type" IN ('comment','direct_message')),
    "object_id" varchar(160) COLLATE belive_unicode_ci NOT NULL,
    "sender_id" varchar(80) COLLATE belive_unicode_ci NOT NULL,
    "sender_name" varchar(120) COLLATE belive_unicode_ci DEFAULT NULL,
    "lead_id" bigint DEFAULT NULL CHECK ("lead_id" BETWEEN 0 AND 4294967295),
    "ref_token" varchar(16) COLLATE belive_unicode_ci DEFAULT NULL,
    "public_reply" varchar(9) COLLATE belive_unicode_ci NOT NULL DEFAULT 'pending' CHECK ("public_reply" IN ('pending','skipped','sent','simulated','failed')),
    "private_reply" varchar(9) COLLATE belive_unicode_ci NOT NULL DEFAULT 'pending' CHECK ("private_reply" IN ('pending','skipped','sent','simulated','failed')),
    "error" varchar(500) COLLATE belive_unicode_ci DEFAULT NULL,
    "claimed_by_lead_id" bigint DEFAULT NULL CHECK ("claimed_by_lead_id" BETWEEN 0 AND 4294967295),
    "claimed_at" timestamp without time zone DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL DEFAULT (statement_timestamp() AT TIME ZONE 'UTC'),
    PRIMARY KEY ("id"),
    CONSTRAINT "social_replies_uq_social_event" UNIQUE ("platform","object_id"),
    CONSTRAINT "social_replies_uq_social_token" UNIQUE ("ref_token")
);

ALTER TABLE "social_replies" ENABLE ROW LEVEL SECURITY;

CREATE TABLE "staff" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" BETWEEN 0 AND 4294967295),
    "name" varchar(80) COLLATE belive_unicode_ci NOT NULL,
    "role" varchar(60) COLLATE belive_unicode_ci NOT NULL DEFAULT 'Viewing agent',
    "wa_phone" varchar(20) COLLATE belive_unicode_ci DEFAULT NULL,
    "email" varchar(120) COLLATE belive_unicode_ci DEFAULT NULL,
    "handles_video" smallint NOT NULL DEFAULT 1,
    "handles_in_person" smallint NOT NULL DEFAULT 1,
    "max_daily_viewings" smallint NOT NULL DEFAULT 8 CHECK ("max_daily_viewings" BETWEEN 0 AND 255),
    "active" smallint NOT NULL DEFAULT 1,
    "created_at" timestamp without time zone NOT NULL DEFAULT (statement_timestamp() AT TIME ZONE 'UTC'),
    PRIMARY KEY ("id")
);

ALTER TABLE "staff" ENABLE ROW LEVEL SECURITY;

CREATE TABLE "staff_shifts" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" BETWEEN 0 AND 4294967295),
    "staff_id" bigint NOT NULL CHECK ("staff_id" BETWEEN 0 AND 4294967295),
    "weekday" smallint NOT NULL CHECK ("weekday" BETWEEN 0 AND 255),
    "starts_at" time NOT NULL,
    "ends_at" time NOT NULL,
    "created_at" timestamp without time zone NOT NULL DEFAULT (statement_timestamp() AT TIME ZONE 'UTC'),
    PRIMARY KEY ("id"),
    CONSTRAINT "staff_shifts_uniq_staff_shift" UNIQUE ("staff_id","weekday","starts_at")
);

ALTER TABLE "staff_shifts" ENABLE ROW LEVEL SECURITY;

CREATE TABLE "staff_time_off" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" BETWEEN 0 AND 4294967295),
    "staff_id" bigint NOT NULL CHECK ("staff_id" BETWEEN 0 AND 4294967295),
    "starts_at" timestamp without time zone NOT NULL,
    "ends_at" timestamp without time zone NOT NULL,
    "reason" varchar(120) COLLATE belive_unicode_ci DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL DEFAULT (statement_timestamp() AT TIME ZONE 'UTC'),
    PRIMARY KEY ("id")
);

ALTER TABLE "staff_time_off" ENABLE ROW LEVEL SECURITY;

CREATE TABLE "tenant_requirements" (
    "lead_id" bigint NOT NULL CHECK ("lead_id" BETWEEN 0 AND 4294967295),
    "location" varchar(100) COLLATE belive_unicode_ci DEFAULT NULL,
    "budget" decimal(10,2) DEFAULT NULL,
    "move_in_date" varchar(100) COLLATE belive_unicode_ci DEFAULT NULL,
    "room_type" varchar(60) COLLATE belive_unicode_ci DEFAULT NULL,
    "tenure" varchar(12) COLLATE belive_unicode_ci DEFAULT NULL,
    "tenant_profile" varchar(40) COLLATE belive_unicode_ci DEFAULT NULL,
    "occupants" smallint DEFAULT NULL CHECK ("occupants" BETWEEN 0 AND 255),
    "amenities" jsonb DEFAULT NULL,
    "preferences" jsonb DEFAULT NULL,
    "updated_at" timestamp without time zone NOT NULL DEFAULT (statement_timestamp() AT TIME ZONE 'UTC'),
    PRIMARY KEY ("lead_id")
);

ALTER TABLE "tenant_requirements" ENABLE ROW LEVEL SECURITY;

CREATE TABLE "verified_listings" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY CHECK ("id" BETWEEN 0 AND 4294967295),
    "room_id" bigint NOT NULL CHECK ("room_id" BETWEEN 0 AND 4294967295),
    "ownership_doc_path" varchar(255) COLLATE belive_unicode_ci DEFAULT NULL,
    "ownership_evidence_version" bigint NOT NULL DEFAULT 0 CHECK ("ownership_evidence_version" BETWEEN 0 AND 4294967295),
    "ownership_verified" smallint NOT NULL DEFAULT 0,
    "ownership_review_status" varchar(13) COLLATE belive_unicode_ci NOT NULL DEFAULT 'not_submitted' CHECK ("ownership_review_status" IN ('not_submitted','pending','approved','rejected')),
    "ownership_review_note" varchar(500) COLLATE belive_unicode_ci DEFAULT NULL,
    "ownership_reviewed_by" varchar(120) COLLATE belive_unicode_ci DEFAULT NULL,
    "ownership_reviewed_at" timestamp without time zone DEFAULT NULL,
    "gps_lat" decimal(10,7) DEFAULT NULL,
    "gps_lng" decimal(10,7) DEFAULT NULL,
    "gps_evidence_version" bigint NOT NULL DEFAULT 0 CHECK ("gps_evidence_version" BETWEEN 0 AND 4294967295),
    "gps_matched" smallint NOT NULL DEFAULT 0,
    "gps_review_status" varchar(13) COLLATE belive_unicode_ci NOT NULL DEFAULT 'not_submitted' CHECK ("gps_review_status" IN ('not_submitted','pending','approved','rejected')),
    "gps_review_note" varchar(500) COLLATE belive_unicode_ci DEFAULT NULL,
    "gps_reviewed_by" varchar(120) COLLATE belive_unicode_ci DEFAULT NULL,
    "gps_reviewed_at" timestamp without time zone DEFAULT NULL,
    "scam_flags" jsonb DEFAULT NULL,
    "scam_checked_at" timestamp without time zone DEFAULT NULL,
    "verified_badge" smallint NOT NULL DEFAULT 0,
    "verified_at" timestamp without time zone DEFAULT NULL,
    "created_at" timestamp without time zone NOT NULL DEFAULT (statement_timestamp() AT TIME ZONE 'UTC'),
    "updated_at" timestamp without time zone NOT NULL DEFAULT (statement_timestamp() AT TIME ZONE 'UTC'),
    PRIMARY KEY ("id"),
    CONSTRAINT "verified_listings_room_id" UNIQUE ("room_id")
);

ALTER TABLE "verified_listings" ENABLE ROW LEVEL SECURITY;

CREATE INDEX "agreement_events_idx_event_agreement" ON "agreement_events" ("agreement_id","id");

CREATE INDEX "ai_activity_log_idx_action" ON "ai_activity_log" ("action");

CREATE INDEX "ai_activity_log_idx_created" ON "ai_activity_log" ("created_at");

CREATE INDEX "ai_activity_log_idx_lead" ON "ai_activity_log" ("lead_id");

CREATE INDEX "ai_feedback_idx_processed" ON "ai_feedback" ("processed");

CREATE INDEX "ai_feedback_idx_interaction" ON "ai_feedback" ("interaction_id");

CREATE INDEX "ai_feedback_fk_feedback_lead" ON "ai_feedback" ("lead_id");

CREATE INDEX "ai_interactions_idx_lead" ON "ai_interactions" ("lead_id");

CREATE INDEX "ai_interactions_idx_direction_date" ON "ai_interactions" ("direction","created_at");

CREATE INDEX "ai_interactions_idx_kind" ON "ai_interactions" ("message_kind");

CREATE INDEX "ai_learned_memory_idx_context_active" ON "ai_learned_memory" ("context_tag","active");

CREATE INDEX "ai_learned_memory_idx_confidence" ON "ai_learned_memory" ("confidence_score");

CREATE INDEX "ai_learned_memory_fk_memory_feedback" ON "ai_learned_memory" ("source_feedback_id");

CREATE INDEX "api_credentials_idx_service_active" ON "api_credentials" ("service","is_active");

CREATE INDEX "bookings_idx_viewing" ON "bookings" ("viewing_datetime");

CREATE INDEX "bookings_idx_status" ON "bookings" ("status");

CREATE INDEX "bookings_fk_bookings_lead" ON "bookings" ("lead_id");

CREATE INDEX "bookings_fk_bookings_room" ON "bookings" ("room_id");

CREATE INDEX "bookings_idx_booking_staff" ON "bookings" ("staff_id","viewing_datetime");

CREATE INDEX "content_post_metrics_idx_metrics_captured" ON "content_post_metrics" ("captured_at");

CREATE INDEX "content_post_metrics_idx_metrics_platform" ON "content_post_metrics" ("platform","captured_on");

CREATE INDEX "content_posts_idx_status" ON "content_posts" ("status");

CREATE INDEX "content_posts_idx_platform" ON "content_posts" ("platform");

CREATE INDEX "content_posts_idx_scheduled" ON "content_posts" ("status","scheduled_for");

CREATE INDEX "content_posts_idx_content_retry" ON "content_posts" ("status","next_retry_at");

CREATE INDEX "digital_agreements_fk_agreement_lead" ON "digital_agreements" ("lead_id");

CREATE INDEX "digital_agreements_fk_agreement_room" ON "digital_agreements" ("room_id");

CREATE INDEX "digital_agreements_idx_agreement_ends_on" ON "digital_agreements" ("ends_on");

CREATE INDEX "digital_agreements_idx_agreement_stage" ON "digital_agreements" ("status");

CREATE INDEX "digital_agreements_idx_agreement_owner" ON "digital_agreements" ("owner_name","status");

CREATE INDEX "electric_bills_idx_bill_tenant" ON "electric_bills" ("lead_id","period_start");

CREATE INDEX "electric_bills_idx_bill_due" ON "electric_bills" ("status","due_on");

CREATE INDEX "leads_idx_status" ON "leads" ("status");

CREATE INDEX "leads_idx_source" ON "leads" ("source_channel");

CREATE INDEX "leads_idx_created" ON "leads" ("created_at");

CREATE INDEX "leads_fk_leads_enquired_room" ON "leads" ("enquired_room_id");

CREATE INDEX "leads_idx_lead_merged" ON "leads" ("merged_into_lead_id");

CREATE INDEX "move_in_logs_idx_room" ON "move_in_logs" ("room_id");

CREATE INDEX "move_in_logs_fk_movein_lead" ON "move_in_logs" ("lead_id");

CREATE INDEX "processed_webhook_messages_idx_pwm_created" ON "processed_webhook_messages" ("created_at");

CREATE INDEX "properties_idx_property_owner" ON "properties" ("owner_name");

CREATE INDEX "properties_idx_property_review_status" ON "properties" ("review_status","created_at");

CREATE INDEX "property_units_idx_unit_property" ON "property_units" ("property_id");

CREATE INDEX "referral_redemptions_idx_redemption_lead" ON "referral_redemptions" ("lead_id","requested_at");

CREATE INDEX "referral_redemptions_idx_redemption_status" ON "referral_redemptions" ("status");

CREATE INDEX "referrals_idx_referring" ON "referrals" ("referring_lead_id");

CREATE INDEX "referrals_idx_referred" ON "referrals" ("referred_lead_id");

CREATE INDEX "referrals_idx_referral_reward_room" ON "referrals" ("reward_room_id");

CREATE INDEX "renewal_offers_idx_offer_agreement" ON "renewal_offers" ("agreement_id","status");

CREATE INDEX "renewal_offers_idx_offer_lead" ON "renewal_offers" ("lead_id","status");

CREATE INDEX "renewal_offers_idx_offer_owner" ON "renewal_offers" ("owner_name","status");

CREATE INDEX "renewal_offers_fk_offer_room" ON "renewal_offers" ("room_id");

CREATE INDEX "room_amenities_idx_room" ON "room_amenities" ("room_id");

CREATE INDEX "room_images_idx_room_sort" ON "room_images" ("room_id","sort_order");

CREATE INDEX "rooms_idx_area_type" ON "rooms" ("location","room_type");

CREATE INDEX "rooms_idx_room_property" ON "rooms" ("property_id");

CREATE INDEX "rooms_idx_room_unit" ON "rooms" ("unit_id");

CREATE INDEX "social_replies_idx_social_lead" ON "social_replies" ("lead_id");

CREATE INDEX "social_replies_idx_social_created" ON "social_replies" ("created_at");

CREATE INDEX "staff_idx_staff_active" ON "staff" ("active");

CREATE INDEX "staff_shifts_idx_shift_weekday" ON "staff_shifts" ("weekday");

CREATE INDEX "staff_time_off_idx_time_off_window" ON "staff_time_off" ("staff_id","starts_at","ends_at");

CREATE INDEX "verified_listings_idx_verified_review_queue" ON "verified_listings" ("ownership_review_status","gps_review_status");

ALTER TABLE "agreement_events" ADD CONSTRAINT "fk_event_agreement" FOREIGN KEY ("agreement_id") REFERENCES "digital_agreements" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ai_feedback" ADD CONSTRAINT "fk_feedback_interaction" FOREIGN KEY ("interaction_id") REFERENCES "ai_interactions" ("id") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ai_feedback" ADD CONSTRAINT "fk_feedback_lead" FOREIGN KEY ("lead_id") REFERENCES "leads" ("id") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ai_interactions" ADD CONSTRAINT "fk_interactions_lead" FOREIGN KEY ("lead_id") REFERENCES "leads" ("id") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ai_learned_memory" ADD CONSTRAINT "fk_memory_feedback" FOREIGN KEY ("source_feedback_id") REFERENCES "ai_feedback" ("id") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "bookings" ADD CONSTRAINT "fk_bookings_lead" FOREIGN KEY ("lead_id") REFERENCES "leads" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "bookings" ADD CONSTRAINT "fk_bookings_room" FOREIGN KEY ("room_id") REFERENCES "rooms" ("id") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "content_post_metrics" ADD CONSTRAINT "fk_metrics_post" FOREIGN KEY ("content_post_id") REFERENCES "content_posts" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "digital_agreements" ADD CONSTRAINT "fk_agreement_lead" FOREIGN KEY ("lead_id") REFERENCES "leads" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "digital_agreements" ADD CONSTRAINT "fk_agreement_room" FOREIGN KEY ("room_id") REFERENCES "rooms" ("id") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "electric_bills" ADD CONSTRAINT "fk_bill_lead" FOREIGN KEY ("lead_id") REFERENCES "leads" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "electric_bills" ADD CONSTRAINT "fk_bill_meter" FOREIGN KEY ("meter_id") REFERENCES "electric_meters" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "electric_meters" ADD CONSTRAINT "fk_meter_room" FOREIGN KEY ("room_id") REFERENCES "rooms" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "leads" ADD CONSTRAINT "fk_leads_enquired_room" FOREIGN KEY ("enquired_room_id") REFERENCES "rooms" ("id") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "move_in_logs" ADD CONSTRAINT "fk_movein_lead" FOREIGN KEY ("lead_id") REFERENCES "leads" ("id") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "move_in_logs" ADD CONSTRAINT "fk_movein_room" FOREIGN KEY ("room_id") REFERENCES "rooms" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "property_units" ADD CONSTRAINT "fk_unit_property" FOREIGN KEY ("property_id") REFERENCES "properties" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "referral_redemptions" ADD CONSTRAINT "fk_redemption_lead" FOREIGN KEY ("lead_id") REFERENCES "leads" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "referrals" ADD CONSTRAINT "fk_ref_referred" FOREIGN KEY ("referred_lead_id") REFERENCES "leads" ("id") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "referrals" ADD CONSTRAINT "fk_ref_referring" FOREIGN KEY ("referring_lead_id") REFERENCES "leads" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "referrals" ADD CONSTRAINT "fk_referral_reward_room" FOREIGN KEY ("reward_room_id") REFERENCES "rooms" ("id") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "renewal_offers" ADD CONSTRAINT "fk_offer_agreement" FOREIGN KEY ("agreement_id") REFERENCES "digital_agreements" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "renewal_offers" ADD CONSTRAINT "fk_offer_lead" FOREIGN KEY ("lead_id") REFERENCES "leads" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "renewal_offers" ADD CONSTRAINT "fk_offer_room" FOREIGN KEY ("room_id") REFERENCES "rooms" ("id") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "room_amenities" ADD CONSTRAINT "fk_amenities_room" FOREIGN KEY ("room_id") REFERENCES "rooms" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "room_images" ADD CONSTRAINT "fk_images_room" FOREIGN KEY ("room_id") REFERENCES "rooms" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "room_pricing" ADD CONSTRAINT "fk_pricing_room" FOREIGN KEY ("room_id") REFERENCES "rooms" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "rooms" ADD CONSTRAINT "fk_room_property" FOREIGN KEY ("property_id") REFERENCES "properties" ("id") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "rooms" ADD CONSTRAINT "fk_room_unit" FOREIGN KEY ("unit_id") REFERENCES "property_units" ("id") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "staff_shifts" ADD CONSTRAINT "fk_shift_staff" FOREIGN KEY ("staff_id") REFERENCES "staff" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "staff_time_off" ADD CONSTRAINT "fk_time_off_staff" FOREIGN KEY ("staff_id") REFERENCES "staff" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tenant_requirements" ADD CONSTRAINT "fk_requirements_lead" FOREIGN KEY ("lead_id") REFERENCES "leads" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "verified_listings" ADD CONSTRAINT "fk_verified_room" FOREIGN KEY ("room_id") REFERENCES "rooms" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

CREATE TRIGGER ai_learned_memory_touch_updated_at BEFORE UPDATE ON "ai_learned_memory" FOR EACH ROW EXECUTE FUNCTION belive_touch_updated_at();

CREATE TRIGGER ai_model_config_touch_updated_at BEFORE UPDATE ON "ai_model_config" FOR EACH ROW EXECUTE FUNCTION belive_touch_updated_at();

CREATE TRIGGER api_credentials_touch_updated_at BEFORE UPDATE ON "api_credentials" FOR EACH ROW EXECUTE FUNCTION belive_touch_updated_at();

CREATE TRIGGER app_settings_touch_updated_at BEFORE UPDATE ON "app_settings" FOR EACH ROW EXECUTE FUNCTION belive_touch_updated_at();

CREATE TRIGGER bookings_touch_updated_at BEFORE UPDATE ON "bookings" FOR EACH ROW EXECUTE FUNCTION belive_touch_updated_at();

CREATE TRIGGER electric_bills_touch_updated_at BEFORE UPDATE ON "electric_bills" FOR EACH ROW EXECUTE FUNCTION belive_touch_updated_at();

CREATE TRIGGER electric_meters_touch_updated_at BEFORE UPDATE ON "electric_meters" FOR EACH ROW EXECUTE FUNCTION belive_touch_updated_at();

CREATE TRIGGER leads_touch_updated_at BEFORE UPDATE ON "leads" FOR EACH ROW EXECUTE FUNCTION belive_touch_updated_at();

CREATE TRIGGER properties_touch_updated_at BEFORE UPDATE ON "properties" FOR EACH ROW EXECUTE FUNCTION belive_touch_updated_at();

CREATE TRIGGER property_units_touch_updated_at BEFORE UPDATE ON "property_units" FOR EACH ROW EXECUTE FUNCTION belive_touch_updated_at();

CREATE TRIGGER renewal_offers_touch_updated_at BEFORE UPDATE ON "renewal_offers" FOR EACH ROW EXECUTE FUNCTION belive_touch_updated_at();

CREATE TRIGGER tenant_requirements_touch_updated_at BEFORE UPDATE ON "tenant_requirements" FOR EACH ROW EXECUTE FUNCTION belive_touch_updated_at();

CREATE TRIGGER verified_listings_touch_updated_at BEFORE UPDATE ON "verified_listings" FOR EACH ROW EXECUTE FUNCTION belive_touch_updated_at();
