CREATE TABLE ai_video_jobs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id bigint NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
    platform varchar(32) NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'queued',
    payload jsonb NOT NULL,
    input_path varchar(500) NOT NULL,
    post_id bigint UNIQUE REFERENCES content_posts(id) ON DELETE SET NULL,
    error_code varchar(40),
    created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at timestamp,
    completed_at timestamp
);
CREATE INDEX idx_ai_video_queue ON ai_video_jobs(status, id);
ALTER TABLE ai_video_jobs ENABLE ROW LEVEL SECURITY;
